### ISSUE TITLE
Do you offer trial?

### ISSUE THREAD

**Issue by kiing98** [doublegram/doublegram_pro#1]
Do you offer trial?

**Comment by doublegram** [comment]
Hi! Doublegram Pro comes with the entire codebase, allowing for advanced customization. We do not offer a trial version for this very reason, but you can fully trust our software. It simply works, and the only limitations are those imposed by Telegram itself (bans, flooding, etc.). You can check all the details about this on doublegram.com/docs/doublegram-pro
